version: '3.4'
services:
  web:
    build: .
    ports: 
      - target: 5000
        published: 80
        protocol: tcp
        mode: host
    entrypoint: "sh -x docker-entrypoint.sh"
    working_dir: "/MTC_Agent/"
    container_name: MTConnect_Agent
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./log/adapter.log
        target: /MTC_Agent/adapter.log
        consistency: delegated